id = "nu"
name = "Nu"
description = "Nushell language support for Zed"
version = "0.0.5"
schema_version = 1
authors = [
  "Mikayla Maki <mikayla@zed.dev>",
  "Joseph Lyons <joseph@zed.dev>",
  "Darren Schroeder",
]
repository = "https://github.com/zed-extensions/nu"

[grammars.nu]
repository = "https://github.com/nushell/tree-sitter-nu"
commit = "2a153c88d5d44d96653057c7cc14292f4e641bef"

[language_servers.nu]
languages = ["Nu"]
name = "nu"
